#!/bin/sh
# $Id$
#
# runs autotools to create ./configure and friends

set -x
aclocal                                 || exit 1
autoheader                              || exit 1
automake --foreign --add-missing --copy || exit 1
autoconf                                || exit 1
